### ISSUE TITLE
Exception thrown in _get_combined_keywords

### ISSUE THREAD

**Issue by SteveWSteele** [summanlp/textrank#3]
Can reproduce issue using the following:

import summa
badLine = 'The present invention provides prodrugs of selective androgen receptor modulators (SARMs), and their use in treating or reducing the incidence of osteoporosis, a variety of hormone-related conditions, conditions associated with Androgen Decline in Aging Male (ADAM); muscular wasting conditions, obesity, dry eye conditions, and prostate cancer.'
keywords = summa.keywords.keywords(' '.join([badLine])).split('\n')

Results in the following:
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ssteele/.local/lib/python2.7/site-packages/summa/keywords.py", line 212, in keywords
    combined_keywords = _get_combined_keywords(keywords, text.split())
  File "/home/ssteele/.local/lib/python2.7/site-packages/summa/keywords.py", line 157, in _get_combined_keywords
    for keyword in combined_word: _keywords.pop(keyword)
KeyError: u'conditions'

A stopgap fix may be to replace line keywords.py:157:
                    for keyword in combined_word: _keywords.pop(keyword)
with:
                    for keyword in combined_word:
                        try:
                            _keywords.pop(keyword)
                        except:
                            pass

This change results in keywords evaluating to:
[u'androgen', u'conditions conditions', u'male', u'invention provides', u'modulators']

**Comment by pgalilea** [comment]
Same problem here

**Comment by amitamisra** [comment]
same problem

**Comment by TinaHongBu** [comment]
same here

**Comment by rohitsakala** [comment]
Same problem

**Comment by fbarrios** [comment]
@rohitsakala Which Python and summa version are you using? Could you please share (in private at least) the entire text that throws the exception?

**Comment by fbarrios** [comment]
Closing this due to lack of activity. Please reopen if the error persists with the latest version.
