### ISSUE TITLE
UnicodeDecodeError

### ISSUE THREAD

**Issue by tongyongquan** [summanlp/textrank#43]
Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\funny\AppData\Local\Temp\pip-install-7wtogz78\summa\setup.py", line 11, in <module>
        long_description = open('README').read(),
    UnicodeDecodeError: 'gbk' codec can't decode byte 0x93 in position 25: illegal multibyte sequence

**Comment by fbarrios** [comment]
Hi! Thank you for the report. It should be fixed now. Please update to the latest version:

https://pypi.org/project/summa/
